books/api/urls.py
from django.urls import include, path

from rest_framework.routers import DefaultRouter

from .views import *


router = DefaultRouter()
router.register(r'books', BookViewSet, basename='books')
router.register(r'users', UserViewSet, basename='users')
router.register(r'book_relation', UserBookRelationView)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

books/books/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from debug_toolbar.toolbar import debug_toolbar_urls

from web import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('api/v1/', include('api.urls')),
    path('auth/', include('djoser.urls')), # drf: token, jwt urls
    re_path(r'^auth/', include('djoser.urls.authtoken')), # drf: token urls
    re_path(r'^auth/', include('djoser.urls.jwt')), # drf: jwt token
]

if not settings.TESTING:
    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()
    

books/web/urls.py
from django.urls import path, include

from web import views


app_name = 'web'

urlpatterns = [
    path(route='books/<int:pk>/update', view=views.BookUpdateView.as_view(), name='book_update_form'),
    path(route='books/<int:pk>/delete/', view=views.BookDeleteView.as_view(), name='book_confirm_delete'),
    path(route='books/<int:pk>/', view=views.BookDetailView.as_view(), name='book_detail'),
    path(route='books/add/', view=views.BookCreateView.as_view(), name='book_form'),
    path(route='books/', view=views.BookListView.as_view(), name='book_list'),
    path(route='search/', view=views.SearchResultView.as_view(), name='search'),
    path(route='profile/', view=views.profile_view, name='profile'),
    path(route='login/', view=views.WebLoginView.as_view(), name='login'),
    path(route='logout/', view=views.WebLogoutView.as_view(), name='logout'),

    path(route='register/', view=views.RegisterView.as_view(), name='register'),
    path(route='register_confirm/<token>', view=views.register_confirm, name='register_confirm'),

    path(route='password_change/', view=views.ChangePasswordView.as_view(), name='password_change'),
    path(route='password_change_done/', view=views.ChangePasswordDoneView.as_view(), name='password_change_done'),

    path(route='password_reset/', view=views.ResetPasswordView.as_view(), name='password_reset'),
    path(route='password_reset/done/', view=views.ResetPasswordDoneView.as_view(), name='password_reset_done'),
    path(route='reset/<token>/', view=views.reset_password_confirm, name="password_reset_confirm"),
    # path('accounts/', include('django.contrib.auth.urls')), # django: auth
]


handler404 = views.page_404

books/web/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Reader(AbstractUser):
    username = models.CharField(
        _("username"),
        max_length=150,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[AbstractUser.username_validator],
        # error_messages={
        #     "unique": _("A user with that username already exists."),
        # },
        null=False,
        blank=False,
    )

    email = models.EmailField(_("email address"), unique=True)

    is_active = models.BooleanField(
        _("active"),
        default=False,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.username}'


class Book(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    author = models.CharField(max_length=100, verbose_name='Автор')
    about = models.CharField(max_length=500, blank=True, default='', verbose_name='О книге')
    added_by = models.ForeignKey(Reader, null=True, on_delete=models.SET_NULL, related_name='my_books', verbose_name='Кем добавлено')
    readers = models.ManyToManyField(to=Reader, through='UserBookRelation', related_name='books', verbose_name='Читатели')


    def __str__(self):
        return f'{self.title}, {self.author}'
    
    def get_absolute_url(self):
        return reverse(viewname='web:book_detail', kwargs={'pk': self.pk}) 
    
    
    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги' 
        ordering = ('id',)


class UserBookRelation(models.Model):
    RATE_CHOISE = (
        (1, 'Bad'),
        (2, 'Ok'),
        (3, 'Good')
    )
    user = models.ForeignKey(Reader, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    like = models.BooleanField(default=False)
    in_bookmarks = models.BooleanField(default=False)
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOISE, null=True)


    def __str__(self):
        return f'{self.book.title}, {self.user.username}, Like: {self.like}, Bookmark: {self.in_bookmarks}, Rate: {self.rate}'


    class Meta:
        verbose_name = "Связь 'пользователь-книга': лайк, закладка, рейтинг"
        ordering = ('id',)

books/web/templates/web/base.html
<!DOCTYPE html>

<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>
      {% block title %}
      Книги
      {% endblock title %}
    </title>
  </head>

  <body>
    {% include "components/navbar.html" %}
	<div class="content-text">
	{% include "components/message.html" %}
    {% block body %}
    {% endblock body %}
	</div>
{% comment %} 


<!-- Блок контента -->
<div class="content-text">
{% block content %}
{% endblock %}

{% if page_obj.has_other_pages %}
	<nav class="list-pages">
		<ul>
			{% if page_obj.has_previous %}
			<li class="page_num">
				<a href="?page={{ page_obj.previous_page_number }}&q={{ query|urlencode }}">&lt;</a>
			</li>
			{% endif %}

			{% for p in paginator.page_range %}
				{% if page_obj.number == p %}
					<li class="page-num page-num-selected">{{ p }}</li>
				{% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
					<li class="page-num">
						<a href="?page={{ p }}&q={{ query|urlencode }}">{{ p }}</a>
					</li>
				{% endif %}
			{% endfor %}

			{% if page_obj.has_next %}
			<li class="page_num">
				<a href="?page={{ page_obj.next_page_number }}&q={{ query|urlencode }}">&gt;</a>
			</li>
			{% endif %}
		</ul>
	</nav>
{% endif %}
</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>

</body> {% endcomment %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>

  <footer>
  Все права не защищены. (с)
  {% block footer %}
  
  {% endblock footer %}
  </footer>

</html>

books/web/templates/web/book_confirm_delete.html
{% extends "base.html" %}

{% block title %}
Удалить книгу {{ book }}
{% endblock title %}

{% block body %}

<h3>Удалить книгу {{ book }}</h3>

<p>Вы уверены, что хотите удалить книгу {{ book }}?</p>

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Удалить">
</form>

<div> 
  <a href="{% url 'web:book_detail' pk=book.pk %}">Назад к книге</a>
</div>

{% endblock body %} 

books/web/templates/web/book_detail.html
{% extends "base.html" %}

{% block title %}
{{ book }}
{% endblock title %}

{% block body %}

<p>Название: {{ book.title }}</p>
<p>Автор: {{ book.author }}</p>

{% if book.about %}
<p>О книге: {{ book.about }}</p>
{% endif %}

{% if book.added_by %}
<p>Добавлена: {{ book.added_by }}</p>
{% endif %}

{% if book.readers.all %}
<p>Прочитали: {{ book.readers.all|join:", " }}</p>
{% endif %}

{% if request.user.is_authenticated %}

  {% if perms.web.change_book %}
  <div> 
    <a href="{% url 'web:book_update_form' pk=book.pk %}">Изменить книгу</a>
  </div>
  {% endif %}

  {% if perms.web.delete_book %}
  <div> 
    <a href="{% url 'web:book_confirm_delete' pk=book.pk %}">Удалить книгу</a>
  </div>
  {% endif %}

{% endif %}

{% endblock body %} 

books/web/templates/web/book_form.html
{% extends "base.html" %}

{% block title %}
Добавить новую книгу
{% endblock title %}

{% block body %}

<h3>Добавить новую книгу</h3>

<form method="POST">
  {% csrf_token %}

  {% for field in form %}
  <div class="mb-3">
    <label class="form-label">{{ field.label }}</label>
    {{ field }}
  </div>
  {% endfor %}

  <button type="submit">Добавить книгу</button> 
</form>

{% endblock body %} 

books/web/templates/web/book_list.html
{% extends "base.html" %}

{% block body %}

<ul class="list-group">
{% for book in books %}
  <li class="list-group-item">
    <div class="clear"></div>
    <a href="{% url 'web:book_detail' pk=book.pk %}">{{ book }}</a>
  </li>
{% endfor %}
</ul>

{% endblock body %}

books/web/templates/web/book_update_form.html
{% extends "base.html" %}

{% block title %}
Изменить книгу {{ book }}
{% endblock title %}

{% block body %}
<h3>Изменить книгу {{ book }}</h3>

<form method="POST">
  {% csrf_token %}
    
  {{ form.as_p }} 

  <button type="submit">Сохранить изменения</button> 
</form>

<div> 
  <a href="{% url 'web:book_detail' pk=book.pk %}">Назад к книге</a>
</div>

{% endblock body %} 

books/web/templates/web/index.html
{% extends "base.html" %}

{% block body %}

{% endblock body %}

books/web/templates/web/profile.html
{% extends "base.html" %}

{% block title %}
Профиль пользователя
{% endblock title %}

{% block body %}

<h3>Профиль пользователя {{ user }}</h3>

<p>Username: {{ user.username }}</p>

{% if user.email %}
<p>Email: {{user.email}}</p>
{% endif %}

<form method="POST" action="{% url 'web:logout' %}">
  {% csrf_token %}
  <button type="submit">Выйти из аккаунта</button> 
</form>

<form method="POST" action="{% url 'web:password_change' %}">
  {% csrf_token %}
   <button type="submit">Сменить пароль</button> 
</form>

{% endblock body %} 

books/web/templates/web/search.html
{% extends 'base.html' %}

{% block title %}
Поиск
{% endblock title %}

{% block body %}

<h3>{{ title }}</h3>
<p>Найденные результаты: {{ result_num }}</p>

{% if result_num == 0 %}
<p>Убедитесь, что используете кириллицу и пишите имя с заглавной буквы.</p>
{% endif %}

<ul class="list-group">
{% for book in books %}
  <li class="list-group-item">
    <div class="clear"></div>
    <a href="{% url 'web:book_detail' pk=book.pk %}">{{book}}</a>
  </li>
{% endfor %}
</ul>

{% endblock %}