books/api/urls.py
from django.urls import include, path

from rest_framework.routers import DefaultRouter

from .views import *


router = DefaultRouter()
router.register(r'books', BookViewSet, basename='books')
router.register(r'users', UserViewSet, basename='users')
router.register(r'book_relation', UserBookRelationView)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

books/books/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from debug_toolbar.toolbar import debug_toolbar_urls

from web import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('api/v1/', include('api.urls')),
    path('auth/', include('djoser.urls')), # drf: token, jwt urls
    re_path(r'^auth/', include('djoser.urls.authtoken')), # drf: token urls
    re_path(r'^auth/', include('djoser.urls.jwt')), # drf: jwt token
]

if not settings.TESTING:
    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()
    

books/web/urls.py
from django.urls import path, include

from web import views


app_name = 'web'

urlpatterns = [
    path(route='books/<int:pk>/update', view=views.BookUpdateView.as_view(), name='book_update_form'),
    path(route='books/<int:pk>/delete/', view=views.BookDeleteView.as_view(), name='book_confirm_delete'),
    path(route='books/<int:pk>/', view=views.BookDetailView.as_view(), name='book_detail'),
    path(route='books/add/', view=views.BookCreateView.as_view(), name='book_form'),
    path(route='books/', view=views.BookListView.as_view(), name='book_list'),
    path(route='search/', view=views.SearchResultView.as_view(), name='search'),
    path(route='profile/', view=views.profile_view, name='profile'),
    path(route='login/', view=views.WebLoginView.as_view(), name='login'),
    path(route='logout/', view=views.WebLogoutView.as_view(), name='logout'),

    path(route='register/', view=views.RegisterView.as_view(), name='register'),
    path(route='register_confirm/<token>', view=views.register_confirm, name='register_confirm'),

    path(route='password_change/', view=views.ChangePasswordView.as_view(), name='password_change'),
    path(route='password_change_done/', view=views.ChangePasswordDoneView.as_view(), name='password_change_done'),

    path(route='password_reset/', view=views.ResetPasswordView.as_view(), name='password_reset'),
    path(route='password_reset/done/', view=views.ResetPasswordDoneView.as_view(), name='password_reset_done'),
    path(route='reset/<token>/', view=views.reset_password_confirm, name="password_reset_confirm"),
    # path('accounts/', include('django.contrib.auth.urls')), # django: auth
]


handler404 = views.page_404

books/web/templates/web/components/message.html
{% if messages %}
<ul class="messages">
{% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    Important: 
    {% endif %}
    {{ message }}
  </li>
{% endfor %}
</ul>
{% endif %}

books/web/templates/web/components/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      {% comment %} <a class="navbar-brand" href="{% url 'web:book_list' %}">Книги</a> {% endcomment %}

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:book_list' %}">На главную</a>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:book_form' %}">Добавить книгу</a>
        </li>
        {% endif %}

        <li class="nav-item">
          <form class="d-flex" role="search" action="{% url 'web:search' %}" method="get">
              {% csrf_token %}
              <input name="q" class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
              <button class="btn btn-outline-success" type="submit"><i class="icon icon-search"></i>Поиск</button>
          </form>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:profile' %}">{{ user.username }} | </a>
        </li>

        <li class="nav-item">
          <form method="POST" action="{% url 'web:logout' %}">
            {% csrf_token %}
          <button type="submit">Выйти</button> 
          </form>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:register' %}">Зарегистрироваться</a>
        </li>
        {% endif %}
        
        </ul>
    </div>
  </div>
</nav>